import React, { useState } from 'react'
import './Memes.css'

const allMemes = [
  {
    id: 1,
    img: '/images/meme-muscle.png',
    caption: 'Liquidated 145 times. Still built different. 💪',
    tag: 'GYM BRO',
  },
  {
    id: 2,
    img: '/images/meme-pizza.png',
    caption: "The whole crypto forest feasting on Big Brother's liquidity 🍕",
    tag: 'COMMUNITY FEAST',
  },
  {
    id: 3,
    img: '/images/meme-whale.png',
    caption: 'Machi vs the market. He has a pigeon. He will win. 🐦',
    tag: 'WHALE HUNTER',
  },
  {
    id: 4,
    img: '/images/meme-fantasy.png',
    caption: 'Coffee. Mountains. 25x. Same energy. ☕',
    tag: 'ZEN MODE',
  },
  {
    id: 5,
    img: '/images/meme-monk.png',
    caption: '888 — Something very good is coming your way. Trust Big Brother 🙏',
    tag: 'SPIRITUAL',
  },
  {
    id: 6,
    img: '/images/meme-viking.png',
    caption: 'How Machi handles a bad Twitter ratio ⚡',
    tag: 'BERSERKER',
  },
  {
    id: 7,
    img: '/images/meme-space.png',
    caption: 'Already thinking about the next 25x from orbit 🌍',
    tag: 'GALAXY BRAIN',
  },
  {
    id: 8,
    img: '/images/meme-puppet.png',
    caption: 'Big Brother pulling the strings of the entire market 🎭',
    tag: 'PUPPET MASTER',
  },
  {
    id: 9,
    img: '/images/meme-cartoon.png',
    caption: 'The smile of a man who just re-opened after liquidation 😁',
    tag: 'UNBOTHERED',
  },
  {
    id: 10,
    img: '/images/meme-bayc.png',
    caption: 'The man and his ape. A love story. 🦍',
    tag: 'APE GANG',
  },
  {
    id: 11,
    img: '/images/memes1/1.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 12,
    img: '/images/memes1/2.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 13,
    img: '/images/memes1/AEq49mbX-8dTsUHV.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 14,
    img: '/images/memes1/Gemini_Generated_Image_cctgnvcctgnvcctg.png',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 15,
    img: '/images/memes1/HCfF0C3XIAArBvY.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 16,
    img: '/images/memes1/HCfsqQabMAEnL3s.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 17,
    img: '/images/memes1/HCftgJJXcAADsbm.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 18,
    img: '/images/memes1/HCfzh8eW4AA6QAj.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 19,
    img: '/images/memes1/HCg48wwawAAYBdx.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 20,
    img: '/images/memes1/HCgiH9xWoAAUvt6.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 21,
    img: '/images/memes1/HCgoCPgWkAA3O0l.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 22,
    img: '/images/memes1/HCgqdOYXYAE6CNd.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 23,
    img: '/images/memes1/HCgsJ0UboAA3jcf.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 24,
    img: '/images/memes1/HCgvT3BXkAAB0ig.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 25,
    img: '/images/memes1/HCgvvu3XUAIUujJ.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 26,
    img: '/images/memes1/HChH1TmXkAATVzu.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 27,
    img: '/images/memes1/HChUz2vWoAAL5fL.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 28,
    img: '/images/memes1/HCk-ZxiWMAENQ68.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 29,
    img: '/images/memes1/HCk6MiMWEAA1PF_.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 30,
    img: '/images/memes1/HCk6jeQWAAEFJjO.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 31,
    img: '/images/memes1/HCk7iFCXIAAmrZV.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 32,
    img: '/images/memes1/HCkEfN9WQAAVs4R.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 33,
    img: '/images/memes1/HCkNhbqX0AAlukS.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 34,
    img: '/images/memes1/HCk_wW0XkAAB1-C.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 35,
    img: '/images/memes1/HCl0-PJawAIkgeW.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 36,
    img: '/images/memes1/HCl2GweaQAA0BZb.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 37,
    img: '/images/memes1/HClG8RnWsAAMHig.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 38,
    img: '/images/memes1/HClN4kOWYAEsnx6.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 39,
    img: '/images/memes1/HClQ-n6XgAI9K6U.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 40,
    img: '/images/memes1/HClTVZIWQAAQ8_J.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 41,
    img: '/images/memes1/HClW0oWawAkKrLV.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 42,
    img: '/images/memes1/HClZk66XcAEwaH6.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 43,
    img: '/images/memes1/HClZvecbAAAH7b3.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 44,
    img: '/images/memes1/HCleiaDW4AAjghH.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 45,
    img: '/images/memes1/HClhGUPX0AAPaBj.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 46,
    img: '/images/memes1/HCliEzQXUAApaCE.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 47,
    img: '/images/memes1/HClmhXGawAADZQQ.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 48,
    img: '/images/memes1/HCm2ZM6XsAAEg4O.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 49,
    img: '/images/memes1/HCm4AnXawAU9B0H.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 50,
    img: '/images/memes1/HCm59fbXoAE9W-D.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 51,
    img: '/images/memes1/HCmBMmzaMAAGHUE.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 52,
    img: '/images/memes1/HCmBxXTX0AIS96y.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 53,
    img: '/images/memes1/HCmC8ggXoAAL1Xf.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 54,
    img: '/images/memes1/HCmEnnsX0AEd8LP.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 55,
    img: '/images/memes1/HCmKeaaawAAva91.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 56,
    img: '/images/memes1/HCmM2S6awAQNDxx.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 57,
    img: '/images/memes1/HCmNzp0W4AEdQ0W.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 58,
    img: '/images/memes1/HCmRnAOXkAAWTNc.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 59,
    img: '/images/memes1/HCmVoHfawAALaBR.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 60,
    img: '/images/memes1/HCmd33yWAAAjElN.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 61,
    img: '/images/memes1/HCmsAi5WUAEIYlf.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 62,
    img: '/images/memes1/HCn3BUGXYAAMPCL.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 63,
    img: '/images/memes1/HCnEy-NbwAAu2yJ.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 64,
    img: '/images/memes1/HCnNTRgXIAAtdCa.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 65,
    img: '/images/memes1/HCnPb5UbUAAVYWW.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 66,
    img: '/images/memes1/HCnVIwOXsAE_skQ.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 67,
    img: '/images/memes1/HCngmpiawAIk7mn.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 68,
    img: '/images/memes1/HCnomLNaMAAb2Dq.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 69,
    img: '/images/memes1/HCoGuv8awAIdCjj.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 70,
    img: '/images/memes1/HCoKSurWoAA6s9v.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 71,
    img: '/images/memes1/HCooBZCWgAEvQwf.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 72,
    img: '/images/memes1/HCov9CEWgAAQiLw.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 73,
    img: '/images/memes1/HCpJsA9W4AAJBVD.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 74,
    img: '/images/memes1/HCpTzNtXMAAcY_v.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 75,
    img: '/images/memes1/HCpwb_nW4AEkJzf.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 76,
    img: '/images/memes1/NME2Q3Qyhlh23CSn.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 77,
    img: '/images/memes1/e (8).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 78,
    img: '/images/memes1/gg.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 79,
    img: '/images/memes1/hero-main.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 80,
    img: '/images/memes1/image.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 81,
    img: '/images/memes1/photo_2026-03-06_06-47-29.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 82,
    img: '/images/memes1/photo_2026-03-06_06-47-34.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 83,
    img: '/images/memes1/photo_2026-03-06_06-47-40.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 84,
    img: '/images/memes1/photo_2026-03-06_06-47-48.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 85,
    img: '/images/memes1/photo_2026-03-06_06-47-57.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 86,
    img: '/images/memes1/photo_2026-03-06_06-48-16.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 87,
    img: '/images/memes1/photo_2026-03-06_06-48-21.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 88,
    img: '/images/memes1/photo_2026-03-06_06-48-25.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 89,
    img: '/images/memes1/photo_2026-03-06_06-48-33.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 90,
    img: '/images/memes1/photo_2026-03-06_06-48-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 91,
    img: '/images/memes1/photo_2026-03-06_06-48-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 92,
    img: '/images/memes1/photo_2026-03-06_06-48-46.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 93,
    img: '/images/memes1/photo_2026-03-06_06-48-52.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 94,
    img: '/images/memes1/photo_2026-03-06_06-49-03.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 95,
    img: '/images/memes1/photo_2026-03-06_06-49-09.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 96,
    img: '/images/memes1/photo_2026-03-06_06-49-13.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 97,
    img: '/images/memes1/photo_2026-03-06_06-49-19.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 98,
    img: '/images/memes1/photo_2026-03-06_06-49-24.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 99,
    img: '/images/memes1/photo_2026-03-06_06-49-35.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 100,
    img: '/images/memes1/photo_2026-03-06_06-49-40.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 101,
    img: '/images/memes1/photo_2026-03-06_06-49-45.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 102,
    img: '/images/memes1/photo_2026-03-06_06-49-49.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 103,
    img: '/images/memes1/photo_2026-03-06_06-49-54.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 104,
    img: '/images/memes1/photo_2026-03-06_06-49-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 105,
    img: '/images/memes1/photo_2026-03-06_06-50-04.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 106,
    img: '/images/memes1/photo_2026-03-06_06-50-09.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 107,
    img: '/images/memes1/photo_2026-03-06_06-50-13.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 108,
    img: '/images/memes1/photo_2026-03-06_06-50-18.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 109,
    img: '/images/memes1/photo_2026-03-06_06-50-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 110,
    img: '/images/memes1/photo_2026-03-06_10-51-57.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 111,
    img: '/images/memes1/photo_2026-03-06_12-22-00.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 112,
    img: '/images/memes1/photo_2026-03-06_12-22-05.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 113,
    img: '/images/memes1/photo_2026-03-06_12-22-11.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 114,
    img: '/images/memes1/photo_2026-03-06_12-22-17.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 115,
    img: '/images/memes1/photo_2026-03-06_12-22-26.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 116,
    img: '/images/memes1/photo_2026-03-06_12-22-32.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 117,
    img: '/images/memes1/photo_2026-03-06_12-22-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 118,
    img: '/images/memes1/photo_2026-03-06_12-22-44.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 119,
    img: '/images/memes1/photo_2026-03-06_12-22-50.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 120,
    img: '/images/memes1/photo_2026-03-06_12-22-57.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 121,
    img: '/images/memes1/photo_2026-03-06_12-23-03.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 122,
    img: '/images/memes1/photo_2026-03-06_12-23-09.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 123,
    img: '/images/memes1/photo_2026-03-06_12-23-16.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 124,
    img: '/images/memes1/photo_2026-03-06_12-23-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 125,
    img: '/images/memes1/photo_2026-03-06_12-23-27.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 126,
    img: '/images/memes1/photo_2026-03-06_12-23-39.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 127,
    img: '/images/memes1/photo_2026-03-06_12-23-45.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 128,
    img: '/images/memes1/photo_2026-03-06_12-23-50.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 129,
    img: '/images/memes1/photo_2026-03-06_12-23-56.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 130,
    img: '/images/memes1/photo_2026-03-06_12-24-00.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 131,
    img: '/images/memes1/photo_2026-03-06_12-24-06.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 132,
    img: '/images/memes1/photo_2026-03-06_12-24-12.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 133,
    img: '/images/memes1/photo_2026-03-06_12-24-18.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 134,
    img: '/images/memes1/photo_2026-03-06_12-24-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 135,
    img: '/images/memes1/photo_2026-03-06_12-24-29.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 136,
    img: '/images/memes1/photo_2026-03-06_12-24-34.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 137,
    img: '/images/memes1/photo_2026-03-06_12-24-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 138,
    img: '/images/memes1/photo_2026-03-06_12-24-45.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 139,
    img: '/images/memes1/photo_2026-03-06_12-24-53.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 140,
    img: '/images/memes1/photo_2026-03-06_12-24-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 141,
    img: '/images/memes1/photo_2026-03-06_12-25-05.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 142,
    img: '/images/memes1/photo_2026-03-06_12-25-10.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 143,
    img: '/images/memes1/photo_2026-03-06_12-25-14.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 144,
    img: '/images/memes1/photo_2026-03-06_12-25-21.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 145,
    img: '/images/memes1/photo_2026-03-06_12-25-26.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 146,
    img: '/images/memes1/photo_2026-03-06_12-25-32.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 147,
    img: '/images/memes1/photo_2026-03-06_12-25-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 148,
    img: '/images/memes1/photo_2026-03-06_12-25-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 149,
    img: '/images/memes1/photo_2026-03-06_12-25-49.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 150,
    img: '/images/memes1/photo_2026-03-06_12-25-53.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 151,
    img: '/images/memes1/photo_2026-03-06_12-26-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 152,
    img: '/images/memes1/photo_2026-03-06_12-26-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 153,
    img: '/images/memes1/photo_2026-03-06_12-26-32.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 154,
    img: '/images/memes1/photo_2026-03-06_12-26-39.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 155,
    img: '/images/memes1/photo_2026-03-06_12-26-51.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 156,
    img: '/images/memes1/photo_2026-03-06_12-26-57.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 157,
    img: '/images/memes1/photo_2026-03-06_12-27-03.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 158,
    img: '/images/memes1/photo_2026-03-06_12-27-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 159,
    img: '/images/memes1/photo_2026-03-07_10-16-28.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 160,
    img: '/images/memes1/photo_2026-03-07_10-19-01.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 161,
    img: '/images/memes1/photo_2026-03-07_10-38-56.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 162,
    img: '/images/memes1/photo_2026-03-07_18-35-02.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 163,
    img: '/images/memes1/photo_2026-03-07_19-02-55.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 164,
    img: '/images/memes1/photo_2026-03-07_19-02-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 165,
    img: '/images/memes1/photo_2026-03-07_19-03-05.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 166,
    img: '/images/memes1/photo_2026-03-07_19-03-33.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 167,
    img: '/images/memes1/photo_2026-03-07_19-03-43.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 168,
    img: '/images/memes1/photo_2026-03-07_19-03-51.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 169,
    img: '/images/memes1/photo_2026-03-07_19-04-25.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 170,
    img: '/images/memes1/photo_2026-03-07_19-04-31.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 171,
    img: '/images/memes1/photo_2026-03-07_19-04-35.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 172,
    img: '/images/memes1/photo_2026-03-07_19-04-41.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 173,
    img: '/images/memes1/photo_2026-03-07_19-04-48.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 174,
    img: '/images/memes1/photo_2026-03-07_19-04-52.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 175,
    img: '/images/memes1/photo_2026-03-07_19-04-56.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 176,
    img: '/images/memes1/photo_2026-03-07_19-05-04.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 177,
    img: '/images/memes1/photo_2026-03-07_19-05-07.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 178,
    img: '/images/memes1/photo_2026-03-07_19-05-18.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 179,
    img: '/images/memes1/photo_2026-03-07_19-05-23.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 180,
    img: '/images/memes1/photo_2026-03-07_19-05-30.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 181,
    img: '/images/memes1/photo_2026-03-07_19-05-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 182,
    img: '/images/memes1/photo_2026-03-07_19-05-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 183,
    img: '/images/memes1/photo_2026-03-07_19-05-49.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 184,
    img: '/images/memes1/photo_2026-03-07_19-05-53.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 185,
    img: '/images/memes1/photo_2026-03-07_19-06-00.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 186,
    img: '/images/memes1/photo_2026-03-07_19-07-16.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 187,
    img: '/images/memes1/photo_2026-03-07_23-06-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 188,
    img: '/images/memes1/photo_2026-03-07_23-07-07.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 189,
    img: '/images/memes1/photo_2026-03-07_23-07-10.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 190,
    img: '/images/memes1/photo_2026-03-07_23-07-14.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 191,
    img: '/images/memes1/photo_2026-03-07_23-07-17.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 192,
    img: '/images/memes1/photo_2026-03-07_23-07-21.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 193,
    img: '/images/memes1/photo_2026-03-07_23-07-27.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 194,
    img: '/images/memes1/photo_2026-03-07_23-07-31.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 195,
    img: '/images/memes1/photo_2026-03-07_23-07-35.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 196,
    img: '/images/memes1/photo_2026-03-07_23-07-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 197,
    img: '/images/memes1/photo_2026-03-07_23-07-45.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 198,
    img: '/images/memes1/photo_2026-03-07_23-07-55.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 199,
    img: '/images/memes1/photo_2026-03-07_23-48-36.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 200,
    img: '/images/memes1/photo_2026-03-07_23-48-40.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 201,
    img: '/images/memes1/photo_2026-03-07_23-48-47.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 202,
    img: '/images/memes1/photo_2026-03-07_23-48-54.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 203,
    img: '/images/memes1/photo_2026-03-07_23-49-00.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 204,
    img: '/images/memes1/photo_2026-03-07_23-49-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 205,
    img: '/images/memes1/photo_2026-03-07_23-49-17.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 206,
    img: '/images/memes1/photo_2026-03-07_23-49-24.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 207,
    img: '/images/memes1/photo_2026-03-07_23-49-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 208,
    img: '/images/memes1/photo_2026-03-07_23-49-47.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 209,
    img: '/images/memes1/photo_2026-03-07_23-49-54.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 210,
    img: '/images/memes1/photo_2026-03-07_23-50-01.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 211,
    img: '/images/memes1/u5FzHlYVoqKq8V-I.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 212,
    img: '/images/memes1/unnamed (1).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 213,
    img: '/images/memes1/unnamed (10).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 214,
    img: '/images/memes1/unnamed (11).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 215,
    img: '/images/memes1/unnamed (12).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 216,
    img: '/images/memes1/unnamed (13).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 217,
    img: '/images/memes1/unnamed (14).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 218,
    img: '/images/memes1/unnamed (16).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 219,
    img: '/images/memes1/unnamed (17).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 220,
    img: '/images/memes1/unnamed (18).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 221,
    img: '/images/memes1/unnamed (19).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 222,
    img: '/images/memes1/unnamed (2).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 223,
    img: '/images/memes1/unnamed (20).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 224,
    img: '/images/memes1/unnamed (21).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 225,
    img: '/images/memes1/unnamed (22).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 226,
    img: '/images/memes1/unnamed (23).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 227,
    img: '/images/memes1/unnamed (24).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 228,
    img: '/images/memes1/unnamed (25).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 229,
    img: '/images/memes1/unnamed (26).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 230,
    img: '/images/memes1/unnamed (27).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 231,
    img: '/images/memes1/unnamed (3).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 232,
    img: '/images/memes1/unnamed (5).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 233,
    img: '/images/memes1/unnamed (6).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 234,
    img: '/images/memes1/unnamed (7).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 235,
    img: '/images/memes1/unnamed (8).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 236,
    img: '/images/memes1/unnamed (9).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 237,
    img: '/images/memes1/unnamed (copy).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 238,
    img: '/images/memes1/unnamed.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 239,
    img: '/images/memes1/HCm489qW4AAfVG6.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 240,
    img: '/images/memes1/HCmyS8cawAAzhu3.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 241,
    img: '/images/memes1/HCoZzMNaoAAno7z.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 242,
    img: '/images/memes1/lucid-origin_Aspect_Ratio_16_9_Style_hyper-detailed_3D_animated_cinematic_frame_Create_a_powe-0.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 243,
    img: '/images/memes1/photo_2026-03-06_06-48-11.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 244,
    img: '/images/memes1/photo_2026-03-06_12-23-34.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 245,
    img: '/images/memes1/photo_2026-03-07_19-07-23.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 246,
    img: '/images/memes1/photo_2026-03-07_19-07-30.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 247,
    img: '/images/memes1/photo_2026-03-07_19-07-35.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 248,
    img: '/images/memes1/photo_2026-03-07_19-07-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 249,
    img: '/images/memes1/photo_2026-03-07_19-07-48.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 250,
    img: '/images/memes1/photo_2026-03-07_19-07-53.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 251,
    img: '/images/memes1/photo_2026-03-07_19-07-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 252,
    img: '/images/memes1/photo_2026-03-07_19-08-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 253,
    img: '/images/memes1/photo_2026-03-07_19-08-53.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 254,
    img: '/images/memes1/photo_2026-03-07_19-08-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 255,
    img: '/images/memes1/photo_2026-03-07_19-09-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 256,
    img: '/images/memes1/photo_2026-03-07_19-09-16.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 257,
    img: '/images/memes1/photo_2026-03-07_19-09-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 258,
    img: '/images/memes1/photo_2026-03-07_19-09-31.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 259,
    img: '/images/memes1/photo_2026-03-07_19-09-47.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 260,
    img: '/images/memes1/photo_2026-03-07_19-12-49.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 261,
    img: '/images/memes1/photo_2026-03-07_19-12-54.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 262,
    img: '/images/memes1/photo_2026-03-07_19-12-57.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 263,
    img: '/images/memes1/photo_2026-03-07_23-07-03.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 264,
    img: '/images/memes1/photo_2026-03-07_23-07-52.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 265,
    img: '/images/memes1/photo_2026-03-08_00-21-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 266,
    img: '/images/memes1/photo_2026-03-09_11-00-41.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 267,
    img: '/images/memes1/photo_2026-03-09_11-00-46.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 268,
    img: '/images/memes1/photo_2026-03-09_11-00-52.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 269,
    img: '/images/memes1/photo_2026-03-09_11-00-59.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 270,
    img: '/images/memes1/photo_2026-03-09_11-01-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 271,
    img: '/images/memes1/photo_2026-03-09_11-01-17.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 272,
    img: '/images/memes1/photo_2026-03-09_11-01-23.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 273,
    img: '/images/memes1/photo_2026-03-09_11-01-34.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 274,
    img: '/images/memes1/photo_2026-03-09_11-01-41.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 275,
    img: '/images/memes1/photo_2026-03-09_11-01-46.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 276,
    img: '/images/memes1/photo_2026-03-09_11-01-52.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 277,
    img: '/images/memes1/photo_2026-03-09_11-02-00.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 278,
    img: '/images/memes1/photo_2026-03-09_11-02-07.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 279,
    img: '/images/memes1/photo_2026-03-09_11-02-10.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 280,
    img: '/images/memes1/photo_2026-03-09_11-02-14.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 281,
    img: '/images/memes1/photo_2026-03-09_11-02-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 282,
    img: '/images/memes1/photo_2026-03-09_11-02-26.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 283,
    img: '/images/memes1/photo_2026-03-09_11-02-34.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 284,
    img: '/images/memes1/photo_2026-03-09_11-02-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 285,
    img: '/images/memes1/photo_2026-03-09_11-02-46.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 286,
    img: '/images/memes1/photo_2026-03-09_11-02-57.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 287,
    img: '/images/memes1/photo_2026-03-09_11-03-01.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 288,
    img: '/images/memes1/photo_2026-03-09_11-03-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 289,
    img: '/images/memes1/unnamed (1) (copy).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 290,
    img: '/images/memes1/unnamed (3) (copy).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 291,
    img: '/images/memes1/unnamed (4).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 292,
    img: '/images/memes1/unnamed (another copy).jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 293,
    img: '/images/memes1/01dad671-5264-4bc2-81cc-13f51cd66d21.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 294,
    img: '/images/memes1/0f94426c-caf4-4410-a590-345c5852173a.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 295,
    img: '/images/memes1/1078a490-45dc-4abe-a10a-9bed7e290674.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 296,
    img: '/images/memes1/10ca66e8-54c9-4452-a77b-9d6326c7a3e0.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 297,
    img: '/images/memes1/2884c501-c627-4588-b96b-511bc8be7a5b.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 298,
    img: '/images/memes1/2d61815e-8f80-4c58-96dc-92d3496c2f16.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 299,
    img: '/images/memes1/2d9c4360-3d62-4847-8f46-346cfa785bbd.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 300,
    img: '/images/memes1/35731706-d7fc-4a94-b73b-7cbb38ca1202.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 301,
    img: '/images/memes1/3aa797ae-2d71-4d96-ae78-7def9084bd8e.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 302,
    img: '/images/memes1/41405229-b6f9-4828-907b-18813df3688f.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 303,
    img: '/images/memes1/44fa4e34-15aa-42d2-bdc2-78b2e8da4598.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 304,
    img: '/images/memes1/454fe0de-7f6a-48be-ba55-9074e6aa0c62.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 305,
    img: '/images/memes1/4566d310-8791-4764-833f-569412a567e6.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 306,
    img: '/images/memes1/50bbcfa7-381c-4b0d-bb3c-c132a505e97e.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 307,
    img: '/images/memes1/6bd3430c-d906-46c2-829c-30ccffc3d6c2.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 308,
    img: '/images/memes1/71d28ab5-4fc2-417b-a517-7cd833f1f292.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 309,
    img: '/images/memes1/83468d9c-cca9-4eed-bc65-3785cc7edbeb.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 310,
    img: '/images/memes1/859e7eef-c972-4c4c-8d08-ee2a92bf1b27.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 311,
    img: '/images/memes1/94355cec-3a1b-44fa-bb54-ee2f4b0b43ac.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 312,
    img: '/images/memes1/9f5af49e-8634-465e-8c95-3c7963dbb849.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 313,
    img: '/images/memes1/1.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 314,
    img: '/images/memes1/555.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 315,
    img: '/images/memes1/55.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 316,
    img: '/images/memes1/5jjj5.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 317,
    img: '/images/memes1/a968a1ed-582f-4f15-9eb0-bf11623b3e08.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 318,
    img: '/images/memes1/a9d62076-68cb-4515-8c16-0becced85110.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 319,
    img: '/images/memes1/b2ac2747-23b5-4535-b3fb-9f6beae8adf7.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 320,
    img: '/images/memes1/b3dbfcb3-926a-42d3-afbc-467e26682a86.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 321,
    img: '/images/memes1/bbb22629-c773-4264-97e0-71d320a8a594.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 322,
    img: '/images/memes1/bc2e4060-b4de-42f5-a731-40b22fe2e3b3.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 323,
    img: '/images/memes1/bc7b7a11-afd3-4ffd-951e-3ee93394e810.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 324,
    img: '/images/memes1/c0308e57-3b91-4e56-804a-e3f094a1e145.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 325,
    img: '/images/memes1/c692e54f-50be-4e36-89cc-d4e447c7fc82.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 326,
    img: '/images/memes1/c9e90db7-b79f-4c81-a718-1884396907f5.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 327,
    img: '/images/memes1/ca318e0f-ad91-4792-9585-468d56a2803e.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 328,
    img: '/images/memes1/cca7fcc6-e5ee-42c0-a3c0-b984420ec37b.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 329,
    img: '/images/memes1/cfe31786-1c9b-4bc2-a9b3-555da16d522c.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 330,
    img: '/images/memes1/cx.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 331,
    img: '/images/memes1/d30b2d6e-93f7-4aad-ac37-f10c2b5603c1.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 332,
    img: '/images/memes1/d344e52d-edda-4d99-b402-443c08ff9a3d.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 333,
    img: '/images/memes1/d355e0a5-4510-4ea6-b59b-b71f20312039.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 334,
    img: '/images/memes1/d89879bd-edc3-4ce6-8c04-37031c4eb096.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 335,
    img: '/images/memes1/da4fc944-5970-418b-9ccc-ee86ce92aff4.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 336,
    img: '/images/memes1/dcc81dba-3fd6-4dbe-b1fc-5d5bbcdb989d.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 337,
    img: '/images/memes1/de.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 338,
    img: '/images/memes1/dgdh.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 339,
    img: '/images/memes1/dsds.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 340,
    img: '/images/memes1/e954ea51-8aa4-48a2-877f-bd53c9015fee.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 341,
    img: '/images/memes1/eb367837-e47e-49bf-a0ee-156edffbe395.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 342,
    img: '/images/memes1/ee8607c4-a30a-4000-8b03-02e3387d6d97.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 343,
    img: '/images/memes1/efef.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 344,
    img: '/images/memes1/ew.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 345,
    img: '/images/memes1/f1b6f97f-db3c-4840-844e-eba035b40595.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 346,
    img: '/images/memes1/f238101c-a688-43a8-b7ba-8474612ac766.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 347,
    img: '/images/memes1/f6cffc7f-7511-43b2-b4ee-86fbe1748b47.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 348,
    img: '/images/memes1/f6f25875-d938-4c30-8b29-f20f9aa668fa.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 349,
    img: '/images/memes1/fdfd.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 350,
    img: '/images/memes1/fgb.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 351,
    img: '/images/memes1/fs.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 352,
    img: '/images/memes1/fss.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 353,
    img: '/images/memes1/gbbbhh.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 354,
    img: '/images/memes1/gd.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 355,
    img: '/images/memes1/gt.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 356,
    img: '/images/memes1/hbbh.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 357,
    img: '/images/memes1/Image_Animation_Request_Granted.mp4',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 358,
    img: '/images/memes1/jjj.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 359,
    img: '/images/memes1/jkk.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 360,
    img: '/images/memes1/nhnh.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 361,
    img: '/images/memes1/photo_2026-03-14_15-05-08.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 362,
    img: '/images/memes1/photo_2026-03-14_15-05-12.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 363,
    img: '/images/memes1/photo_2026-03-14_15-05-20.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 364,
    img: '/images/memes1/photo_2026-03-14_15-05-24.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 365,
    img: '/images/memes1/photo_2026-03-14_15-05-28.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 366,
    img: '/images/memes1/photo_2026-03-21_08-03-26.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 367,
    img: '/images/memes1/photo_2026-03-21_08-03-32.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 368,
    img: '/images/memes1/photo_2026-03-21_08-03-37.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 369,
    img: '/images/memes1/photo_2026-03-21_08-03-43.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 370,
    img: '/images/memes1/photo_2026-03-21_08-03-47.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 371,
    img: '/images/memes1/photo_2026-03-21_08-03-53.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 372,
    img: '/images/memes1/photo_2026-03-21_08-03-58.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 373,
    img: '/images/memes1/photo_2026-03-21_08-04-03.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 374,
    img: '/images/memes1/photo_2026-03-21_08-04-16.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 375,
    img: '/images/memes1/photo_2026-03-21_08-04-22.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 376,
    img: '/images/memes1/photo_2026-03-21_08-04-27.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 377,
    img: '/images/memes1/photo_2026-03-21_08-04-32.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 378,
    img: '/images/memes1/photo_2026-03-21_08-04-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 379,
    img: '/images/memes1/photo_2026-03-21_08-04-42.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 380,
    img: '/images/memes1/photo_2026-03-21_08-04-50.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 381,
    img: '/images/memes1/photo_2026-03-21_08-04-58.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 382,
    img: '/images/memes1/photo_2026-03-21_08-05-02.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 383,
    img: '/images/memes1/photo_2026-03-21_08-05-06.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 384,
    img: '/images/memes1/photo_2026-03-21_08-05-10.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 385,
    img: '/images/memes1/photo_2026-03-21_08-05-14.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 386,
    img: '/images/memes1/photo_2026-03-21_08-05-20.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 387,
    img: '/images/memes1/photo_2026-03-21_08-05-24.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 388,
    img: '/images/memes1/photo_2026-03-21_08-05-30.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 389,
    img: '/images/memes1/photo_2026-03-21_08-05-34.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 390,
    img: '/images/memes1/photo_2026-03-21_08-05-38.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 391,
    img: '/images/memes1/photo_2026-03-21_08-05-43.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 392,
    img: '/images/memes1/photo_2026-03-21_08-05-47.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 393,
    img: '/images/memes1/photo_2026-03-21_08-05-52.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 394,
    img: '/images/memes1/photo_2026-03-21_08-06-13.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 395,
    img: '/images/memes1/photo_2026-03-21_08-06-17.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 396,
    img: '/images/memes1/photo_2026-03-21_08-06-23.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 397,
    img: '/images/memes1/photo_2026-03-21_08-06-27.jpg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 398,
    img: '/images/memes1/rfg.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 399,
    img: '/images/memes1/rgrg.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 400,
    img: '/images/memes1/rr.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 401,
    img: '/images/memes1/shs.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 402,
    img: '/images/memes1/thhh.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 403,
    img: '/images/memes1/th.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 404,
    img: '/images/memes1/Untitled.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 405,
    img: '/images/memes1/vb.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 406,
    img: '/images/memes1/vv.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
  {
    id: 407,
    img: '/images/memes1/yrhd.jpeg',
    caption: 'Machi Community Meme',
    tag: 'COMMUNITY MEME',
  },
]

export default function Memes({ setCurrentPage }) {
  const [lightbox, setLightbox] = useState(null)

  return (
    <section className="memes" id="memes" style={{ paddingTop: '8rem' }}>
      <div className="memes-inner">
        <button
          className="btn-back-home"
          onClick={() => {
            setCurrentPage('home');
            window.scrollTo(0, 0);
          }}
        >
          &larr; Back to Home
        </button>
        {/* Header */}
        <div className="memes-header reveal" style={{ marginTop: '2rem' }}>
          <div className="section-label">Community Memes</div>
          <h2 className="memes-title">
            The Internet Made Him<br />
            <span className="gold-text">A Legend.</span>
          </h2>
          <p className="memes-desc">
            When you lose $74M and the community makes memes instead of mourning.
          </p>
        </div>

        {/* Meme Grid — masonry-style mixed sizes */}
        <div className="meme-grid expanded">
          {allMemes.map((meme, i) => (
            <div
              key={meme.id}
              className={`meme-card reveal ${i === 0 ? 'meme-featured' : ''}`}
              style={{ animationDelay: `${i * 0.07}s` }}
              onClick={() => setLightbox(meme)}
            >
              <div className="meme-img-wrap">
                <img src={meme.img} alt={meme.caption} className="meme-img" loading="lazy" />
                <div className="meme-hover-overlay">
                  <span className="meme-view-btn">View</span>
                </div>
                <span className="meme-tag">{meme.tag}</span>
              </div>
              <p className="meme-caption">{meme.caption}</p>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="memes-cta reveal">
          <span className="cta-text">Got your own Machi meme?</span>
          <a
            href="https://x.com/i/communities/2029464249416684023"
            target="_blank"
            rel="noopener noreferrer"
            className="btn-gold"
          >
            Post In The Community →
          </a>
        </div>
      </div>

      {/* Lightbox */}
      {lightbox && (
        <div className="lightbox" onClick={() => setLightbox(null)}>
          <div className="lightbox-inner" onClick={e => e.stopPropagation()}>
            <button className="lightbox-close" onClick={() => setLightbox(null)}>✕</button>
            <img src={lightbox.img} alt={lightbox.caption} className="lightbox-img" />
            <div className="lightbox-caption">
              <span className="lightbox-tag">{lightbox.tag}</span>
              <p>{lightbox.caption}</p>
            </div>
          </div>
        </div>
      )}
    </section>
  )
}
